import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import QRCode from 'qrcode';

// helper to convert date to Hijri (mocked)
const getHijriDate = () => '1446/10/03';

export const generateTripPDF = async (trip, qrUrl) => {
  const doc = new jsPDF();

  // ----------------- PAGE 1 -------------------
  // Header
  doc.setFontSize(20);
  doc.setTextColor(41, 128, 185);
  doc.text('Passenger Transport Report', 105, 20, { align: 'center' });

  // Company Info
  doc.setFontSize(12);
  doc.setTextColor(40);
  doc.text('Celtco Travelers', 20, 35);
  doc.text('License no. 35/0000058', 20, 42);
  doc.text('CR.4650077231', 20, 49);

  // Trip Details
  doc.setFontSize(14);
  doc.setTextColor(41, 128, 185);
  doc.text('Trip Information', 20, 65);

  doc.setFontSize(12);
  doc.setTextColor(40);
  doc.text(`Driver Name: ${trip.driverName}`, 20, 75);
  doc.text(`Residency Number: ${trip.residencyNumber}`, 20, 82);
  doc.text(`Company: ${trip.company}`, 20, 89);
  doc.text(`Vehicle: ${trip.vehicleType} (${trip.registrationNumber})`, 20, 96);
  doc.text(`Trip Date: ${trip.tripDate}`, 20, 103);
  doc.text(`Total Passengers: ${trip.passengers.length}`, 20, 110);
  doc.text(`Report ID: ${trip.id}`, 20, 117);
  doc.text(`Submission Date: ${new Date(trip.submissionDate).toLocaleString()}`, 20, 124);

  // Passengers Table
  doc.setFontSize(14);
  doc.setTextColor(41, 128, 185);
  doc.text('Passenger List', 20, 140);

  const tableData = trip.passengers.map((p, index) => [
    index + 1,
    p.name,
    p.idNumber,
    p.nationality || 'N/A',
    p.from,
    p.to,
  ]);

  autoTable(doc, {
    startY: 145,
    head: [['#', 'Name', 'ID Number', 'Nationality', 'From', 'To']],
    body: tableData,
    theme: 'grid',
    styles: { fontSize: 10 },
    headStyles: { fillColor: [41, 128, 185] },
    margin: { top: 145 },
  });

  // QR Code
  const qrImage = await QRCode.toDataURL(qrUrl);
  doc.addImage(qrImage, 'PNG', 160, 20, 35, 35);

  // ----------------- PAGE 2 -------------------
  doc.addPage();
  
  // Arabic Header
  doc.setFontSize(16);
  doc.setTextColor(41, 128, 185);
  doc.text('شركة التميز الشاملة الرائدة للنقل', 105, 20, { align: 'center' });
  
  // Dates
  doc.setFontSize(12);
  doc.setTextColor(40);
  doc.text(`التاريخ الهجري: ${getHijriDate()}`, 180, 30, { align: 'right' });
  doc.text(`التاريخ الميلادي: ${trip.tripDate}`, 180, 36, { align: 'right' });

  // Contract Title
  doc.setFontSize(18);
  doc.setTextColor(41, 128, 185);
  doc.text('عقد نقل ركاب بالحافلات', 105, 48, { align: 'center' });

  // Contract Details
  doc.setFontSize(12);
  doc.setTextColor(40);
  doc.text(`الطرف الأول : شركة التميز الشاملة الرائدة للنقل`, 20, 65);
  doc.text(`الطرف الثاني : ${trip.driverName} (رقم الهوية : ${trip.residencyNumber})`, 20, 73);

  // Trip Details
  doc.setFontSize(11);
  doc.text(`تم الاتفاق على قيام الطرف الأول بعملية نقل الطرف الثاني،`, 20, 85);
  doc.text(`نقطة الانطلاق : ${trip.passengers[0]?.from || '---'}`, 20, 95);
  doc.text(`نقطة الوصول : ${trip.passengers[0]?.to || '---'}`, 20, 102);
  doc.text(`عدد الركاب : ${trip.passengers.length}`, 20, 109);
  doc.text(`نوع المركبة : ${trip.vehicleType}`, 20, 116);
  doc.text(`رقم المركبة : ${trip.registrationNumber}`, 20, 123);

  // Terms and Conditions
  doc.setFontSize(10);
  doc.text('سياسة الإلغاء والاستبدال:', 20, 135);
  doc.text('1. يتم الغاء العقد قبل ٢٤ ساعة بدون أي التزامات.', 20, 142);
  doc.text('2. لا يمكن التبديل بعد بدء الرحلة.', 20, 148);
  doc.text('3. يجب على السائق التأكد من هوية جميع الركاب.', 20, 154);
  doc.text('4. يجب الالتزام بجميع قوانين المرور والسلامة.', 20, 160);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text('This is an official document generated by Celtco Travelers', 105, 285, { align: 'center' });
  doc.text('celtco07u@gmail.com', 105, 290, { align: 'center' });

  // Save the PDF
  doc.save(`TripReport_${trip.id}.pdf`);
};
